### ISSUE TITLE
Add requirements.txt, pyproject.toml or other dependency specification

### ISSUE THREAD

**Issue by korsbakken** [MarkMDekker/IAMfingerprints#20]
Hi, and thanks for an interesting paper and very useful-looking code. I'm considering using modified versions of this for diagnostics in two other modelling projects (IAM COMPACT and DIAMOND).

But, I notice that there is no specification of dependencies in the repo, at least not that I could find. Other than implicitly through the import statements, but that doesn't tell you which versions were used. Pandas and xarray introduce breaking changes from time to time, so it's important to know which versions are known to be compatible. Numpy version can also be important in some cases.

Could you add a file with dependency and dependency version info? Possibly both a file that specifies exactly what version you used of python and each 3rd-party package for the paper, and one without pinning the versions, so users can try their luck with the latest version of each package.

The simplest way of doing this would be to add a requirements.txt file (and possibly requirements_paper.txt or something like that for the exact versions used in the paper). pyproject.toml would also be a common and more "modern" way of specifying dependencies, but I guess that is mostly used for installable Python packages, not notebook-based code.

**Comment by MarkMDekker** [comment]
Hi, thanks for your interest. I'll look into this and keep you posted!

**Comment by MarkMDekker** [comment]
Same as my response in #21 . Feel free to contact me directly if you need my direct assistance. But it's still on my list to deal with this in this repository.

**Comment by MarkMDekker** [comment]
Done. I added a (conda-) requirements file.
